### ISSUE TITLE
Set up Firebase, including API keys (but keep them out of the repository using .env).

### ISSUE THREAD

**Issue by veridisyndrome** [BrewR-EPFL/BrewR#5]

**Comment by jeongJ2004** [comment]
Questions to ask to the coaches on 04/10/2024 about setting up firebase phase : 
1. Package name : com.android.sample -> com. ... .brewr 
2. Do we need firestore, if so, should it be in test mode or production mode ?
3. Do we need to encode64 the google-services.json and use secret repository on github ?
